config/routes.rb
Rails.application.routes.draw do
  root 'application#login'
  get 'mail/index'
  get 'authorize' => 'auth#gettoken'
  get 'login' => 'application#login'
  get 'meetings' => 'meetings#index'
  get 'meeting_show_filter' => 'meetings#show_filter'
  resources :notes, only: [:destroy]
  resources :meetings do
    resources :notes
  end
end

app/views/layouts/_head.html.erb
<head>
	<title>Note Taking App</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
		</script>
	<![endif]-->
</head>

app/views/layouts/_nav.html.erb
<section id="header-container">
	<div class="row center">
		<div class="col-sm-6 col-sm-offset-3">
			<div id="today-link">
				<%= link_to meetings_path, remote: true do %>
					<h1><%= todays_date %></h1>
				<% end %>
			</div>
			<p>
				<% if session[:azure_access_token] %>
					Hello <%= session[:username] %>,
					you have
					<span id="num-meetings-for-today">
						<%= pluralize(num_meetings_for_today, "meeting") %>
					</span>
					today.
				<% else %>
					<%= link_to "Please log in", get_login_url %> to view your meetings
					and manage your notes.
				<% end %>
			</p>
		</div>
	</div>
</section>

<section id="filter-container">
	<div class="row center">
		<div class="col-xs-3">
			<%= link_to meeting_show_filter_path(note_type: "pre", index: 0), remote: true do %>
				<i class="fa fa-circle-o fa-2x"></i>
				<br>
				Pre
			<% end %>
		</div>
		<div class="col-xs-3">
			<%= link_to meeting_show_filter_path(note_type: "current", index: 0),
					remote: true do %>
				<i class="fa fa-dot-circle-o fa-2x"></i>
				<br>
				Current
			<% end %>
		</div>
		<div class="col-xs-3">
			<%= link_to meeting_show_filter_path(note_type: "post", index: 0),
					remote: true do %>
				<i class="fa fa-circle fa-2x"></i>
				<br>
				Post
			<% end %>
		</div>
		<div class="col-xs-3 medium-gray">
			<i class="fa fa-sticky-note-o fa-2x"></i>
			<br>
			Notes
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>